#!/bin/sh

source MERGE.CONFIG.FILE

# qiime container name
qiime="qiime2/core:2018.6"

docker run -i -v $mount $qiime /bin/sh -c " \
        cd $artifacts_dir && \
	qiime feature-table merge \
	--i-tables $table_1 \
	--i-tables $table_2 \
	--p-overlap-method sum \
	--o-merged-table ${data_set}-table.qza && \
	qiime feature-table merge-seqs \
	--i-data $seqs_1 \
	--i-data $seqs_2 \
	--o-merged-data ${data_set}-rep-seqs.qza &&\
	qiime feature-table summarize \
        --i-table ${data_set}-table.qza \
        --o-visualization ${data_set}-table.qzv && \
	apt-get update && \
        apt-get install unzip && \
        unzip ${data_set}-table.qzv -d unzipped-table"

#sampling depth
sampling=$(awk -F',' 'END{print $2}' ${artifacts_dir}/unzipped-table/*/data/sample-frequency-detail.csv )
sampling_depth=$(printf "%.0f\n" "$sampling")

# steps 5,6,7,8,9: cluster, phylogeny, core-metrics, classify, barplot

docker run -i -v $mount $qiime /bin/sh -c " \
	cd $artifacts_dir && \
	qiime vsearch cluster-features-open-reference \
	--i-table ${data_set}-table.qza \
	--i-sequences ${data_set}-rep-seqs.qza \
	--i-reference-sequences $ref_seqs \
	--p-perc-identity 0.99 \
	--p-strand both \
	--o-clustered-table ${data_set}-table-or-99.qza \
	--o-clustered-sequences ${data_set}-rep-seqs-or-99.qza \
	--o-new-reference-sequences ${data_set}-new-ref-seqs-or-99 && \
	qiime feature-table filter-features \
	--i-table ${data_set}-table-or-99.qza \
	--p-min-frequency 2 \
	--o-filtered-table ${data_set}-filtered-table-or-99.qza && \
	qiime feature-table tabulate-seqs \
	--i-data ${data_set}-rep-seqs-or-99.qza \
	--o-visualization ${data_set}-rep-seqs-or-99.qzv && \
	qiime alignment mafft \
	--i-sequences ${data_set}-rep-seqs-or-99.qza \
	--o-alignment ${data_set}-aligned-rep-seqs-or-99.qza && \
	qiime alignment mask \
	--i-alignment ${data_set}-aligned-rep-seqs-or-99.qza \
	--o-masked-alignment ${data_set}-masked-aligned-rep-seqs-or-99.qza && \
	qiime phylogeny fasttree \
	--i-alignment ${data_set}-masked-aligned-rep-seqs-or-99.qza \
	--o-tree ${data_set}-unrooted-tree.qza && \
	qiime phylogeny midpoint-root \
	--i-tree ${data_set}-unrooted-tree.qza \
	--o-rooted-tree ${data_set}-rooted-tree.qza && \
	qiime diversity core-metrics-phylogenetic \
	--i-phylogeny ${data_set}-rooted-tree.qza \
	--i-table ${data_set}-table-or-99.qza \
	--p-sampling-depth ${sampling_depth} \
	--m-metadata-file $metadata_file_path \
	--output-dir diversity-statistics && \
	qiime feature-classifier classify-consensus-blast \
        --i-query ${data_set}-rep-seqs-or-99.qza \
        --i-reference-taxonomy $ref_tax \
	--i-reference-reads $ref_seqs \
	--p-perc-identity 0.99 \
        --o-classification ${data_set}-taxonomy.qza && \
	qiime metadata tabulate \
	--m-input-file ${data_set}-taxonomy.qza \
	--o-visualization ${data_set}-taxonomy.qzv && \
	qiime taxa barplot \
	--i-table diversity-statistics/rarefied_table.qza \
	--i-taxonomy ${data_set}-taxonomy.qza \
	--m-metadata-file $metadata_file_path \
	--o-visualization ${data_set}-tax-bar-plots.qzv && \
	qiime taxa collapse \
        --i-table ${data_set}-table-or-99.qza \
        --i-taxonomy ${data_set}-taxonomy.qza \
        --p-level 1 \
        --o-collapsed-table ${data_set}-table-collapsed1.qza && \
        qiime feature-table relative-frequency \
        --i-table ${data_set}-table-collapsed1.qza \
        --o-relative-frequency-table ${data_set}-table1-frequency.qza && \
        qiime tools export ${data_set}-table1-frequency.qza \
        --output-dir frequency-tables && \
        biom convert \
        -i frequency-tables/feature-table.biom -o frequency-tables/level1-feature-table.tsv --to-tsv && \
	qiime taxa collapse \
        --i-table ${data_set}-table-or-99.qza \
        --i-taxonomy ${data_set}-taxonomy.qza \
        --p-level 2 \
        --o-collapsed-table ${data_set}-table-collapsed2.qza && \
        qiime feature-table relative-frequency \
        --i-table ${data_set}-table-collapsed2.qza \
        --o-relative-frequency-table ${data_set}-table2-frequency.qza && \
        qiime tools export ${data_set}-table2-frequency.qza \
        --output-dir frequency-tables && \
        biom convert \
        -i frequency-tables/feature-table.biom -o frequency-tables/level2-feature-table.tsv --to-tsv &&
	qiime taxa collapse \
	--i-table ${data_set}-table-or-99.qza \
	--i-taxonomy ${data_set}-taxonomy.qza \
	--p-level 3 \
	--o-collapsed-table ${data_set}-table-collapsed3.qza && \
	qiime feature-table relative-frequency \
	--i-table ${data_set}-table-collapsed3.qza \
	--o-relative-frequency-table ${data_set}-table3-frequency.qza && \
	qiime tools export ${data_set}-table3-frequency.qza \
	--output-dir frequency-tables && \
	biom convert \
	-i frequency-tables/feature-table.biom -o frequency-tables/level3-feature-table.tsv --to-tsv &&
	qiime taxa collapse \
        --i-table ${data_set}-table-or-99.qza \
        --i-taxonomy ${data_set}-taxonomy.qza \
        --p-level 4 \
        --o-collapsed-table ${data_set}-table-collapsed4.qza && \
        qiime feature-table relative-frequency \
        --i-table ${data_set}-table-collapsed4.qza \
        --o-relative-frequency-table ${data_set}-table4-frequency.qza && \
        qiime tools export ${data_set}-table4-frequency.qza \
        --output-dir frequency-tables && \
        biom convert \
        -i frequency-tables/feature-table.biom -o frequency-tables/level4-feature-table.tsv --to-tsv &&
	qiime taxa collapse \
        --i-table ${data_set}-table-or-99.qza \
        --i-taxonomy ${data_set}-taxonomy.qza \
        --p-level 5 \
        --o-collapsed-table ${data_set}-table-collapsed5.qza && \
        qiime feature-table relative-frequency \
        --i-table ${data_set}-table-collapsed5.qza \
        --o-relative-frequency-table ${data_set}-table5-frequency.qza && \
        qiime tools export ${data_set}-table5-frequency.qza \
        --output-dir frequency-tables && \
        biom convert \
        -i frequency-tables/feature-table.biom -o frequency-tables/level5-feature-table.tsv --to-tsv &&
	qiime taxa collapse \
        --i-table ${data_set}-table-or-99.qza \
        --i-taxonomy ${data_set}-taxonomy.qza \
        --p-level 6 \
        --o-collapsed-table ${data_set}-table-collapsed6.qza && \
        qiime feature-table relative-frequency \
        --i-table ${data_set}-table-collapsed6.qza \
        --o-relative-frequency-table ${data_set}-table6-frequency.qza && \
        qiime tools export ${data_set}-table6-frequency.qza \
        --output-dir frequency-tables && \
        biom convert \
        -i frequency-tables/feature-table.biom -o frequency-tables/level6-feature-table.tsv --to-tsv &&
	qiime taxa collapse \
        --i-table ${data_set}-table-or-99.qza \
        --i-taxonomy ${data_set}-taxonomy.qza \
        --p-level 7 \
        --o-collapsed-table ${data_set}-table-collapsed7.qza && \
        qiime feature-table relative-frequency \
        --i-table ${data_set}-table-collapsed7.qza \
        --o-relative-frequency-table ${data_set}-table7-frequency.qza && \
        qiime tools export ${data_set}-table7-frequency.qza \
        --output-dir frequency-tables && \
        biom convert \
        -i frequency-tables/feature-table.biom -o frequency-tables/level7-feature-table.tsv --to-tsv && \
	mv frequency-tables relative-frequency-tables && \
	apt-get update && \
	apt-get install unzip && \
	unzip ${data_set}-tax-bar-plots.qzv -d barplots && \
	mkdir diversity-statistics/alpha-diversity && \
        mkdir diversity-statistics/beta-diversity && mkdir frequency-tables && \
        mv barplots/*/data/*.csv frequency-tables && \
        mkdir artifacts && \
        mv *.qza artifacts && \
        mkdir visualizations && \
        mv *.qzv visualizations && \
        rm -r barplots && \
        cd diversity-statistics && \
        mv *emperor.qzv beta-diversity"

docker run -i -v $mount $qiime /bin/sh -c " \
        cd $artifacts_dir && \
        qiime diversity alpha \
        --i-table artifacts/${data_set}-table-or-99.qza \
        --p-metric chao1 \
        --o-alpha-diversity diversity-statistics/alpha-diversity/${data_set}-chao1.qza && \
        qiime diversity alpha \
        --i-table artifacts/${data_set}-table-or-99.qza \
        --p-metric simpson \
        --o-alpha-diversity diversity-statistics/alpha-diversity/${data_set}-simpson.qza && \
        qiime diversity alpha \
        --i-table artifacts/${data_set}-table-or-99.qza \
        --p-metric shannon \
        --o-alpha-diversity diversity-statistics/alpha-diversity/${data_set}-shannon.qza && \
        cd diversity-statistics/alpha-diversity && \
        qiime diversity alpha-group-significance \
        --i-alpha-diversity ${data_set}-chao1.qza \
        --m-metadata-file $metadata_file_path \
        --o-visualization ${data_set}-chao1.qzv && \
        qiime diversity alpha-group-significance \
        --i-alpha-diversity ${data_set}-simpson.qza \
        --m-metadata-file $metadata_file_path \
        --o-visualization ${data_set}-simpson.qzv && \
        qiime diversity alpha-group-significance \
        --i-alpha-diversity ${data_set}-shannon.qza \
        --m-metadata-file $metadata_file_path \
        --o-visualization ${data_set}-shannon.qzv"
